import json
import re
from pathlib import Path
from typing import Dict, List


class VibecodeAnalyzer:
    """Lightweight analyzer for Vibecode-related signals and code origin hints."""

    def __init__(self) -> None:
        self.keywords = ["vibecode", "vibe", "prompt-driven", "agent workflow", "autonomous coding"]
        self.weight_map = {
            "vibecode": 2,
            "vibe": 1,
            "prompt-driven": 1,
            "agent workflow": 1,
            "autonomous coding": 1,
        }
        self.llm_indicators = [
            "generated by",
            "generated with",
            "chatgpt",
            "copilot",
            "openai",
            "gpt",
            "llm",
            "ai-generated",
            "ai generated",
            "model-generated",
            "generated code",
            "autogenerated",
            "assistant",
            "generated from prompt",
            "created by model",
            "using llm",
        ]
        self.template_indicators = [
            "template",
            "scaffold",
            "placeholder",
            "boilerplate",
            "stub",
            "skeleton",
            "starter",
            "example code",
            "todo implement",
            "todo:",
        ]
        self.generation_indicators = [
            "generated by",
            "generated with",
            "autogenerated",
            "generated code",
            "generated from prompt",
            "created by model",
            "using llm",
            "copilot",
            "chatgpt",
            "gpt",
            "llm",
            "assistant",
            "synthesized",
            "prompt-driven",
            "agent workflow",
        ]
        self.trace_patterns = [
            r"trace\s*[:=]",
            r"prompt\s*->",
            r"->\s*model",
            r"->\s*patch",
            r"workflow",
            r"pipeline",
            r"agent",
            r"patch",
        ]
        self.intent_patterns = [
            r"intent\s*[:=]",
            r"goal\s*[:=]",
            r"objective\s*[:=]",
            r"aim\s*[:=]",
            r"purpose\s*[:=]",
            r"deliver",
            r"reduce",
            r"improve",
            r"support",
            r"enable",
            r"build",
            r"implement",
        ]
        self.goal_patterns = [
            r"goal\s*[:=]",
            r"objective\s*[:=]",
            r"aim\s*[:=]",
            r"purpose\s*[:=]",
        ]
        self.behavior_weights = {
            "generated_code": 2,
            "autogenerated": 2,
            "template_like": 1,
            "trace_like": 1,
            "intent_like": 1,
        }
        self.code_structure_patterns = [
            r"\bdef\b",
            r"\bclass\b",
            r"\bimport\b",
            r"\breturn\b",
            r"\bfor\b",
            r"\bwhile\b",
            r"\bif\b",
            r"\btry\b",
            r"\bexcept\b",
            r"\basync\b",
        ]

    def analyze(self, text: str, config_path: Path | None = None, config: Dict | None = None) -> Dict:
        normalized = (text or "").lower()
        matched = [keyword for keyword in self.keywords if keyword in normalized]
        behavior = self._detect_behavior(text)
        trace_analysis = self._analyze_trace(text)
        intent_analysis = self._analyze_intent(text)
        config = config if config is not None else self.load_config(config_path)
        dynamic_rules = self._apply_dynamic_rules(text, config)
        profile_name = config.get("profile") if isinstance(config, dict) else None
        profile_config = self._get_profile_config(config, profile_name)
        evidence_breakdown = {
            "behavior": {
                "generated_code": behavior.get("generated_code"),
                "autogenerated": behavior.get("autogenerated"),
                "template_like": behavior.get("template_like"),
                "trace_like": behavior.get("trace_like"),
                "intent_like": behavior.get("intent_like"),
                "evidence": behavior.get("evidence", []),
            },
            "trace": {
                "detected": trace_analysis.get("detected"),
                "evidence": trace_analysis.get("evidence", []),
            },
            "intent": {
                "has_intent": intent_analysis.get("has_intent"),
                "has_goal": intent_analysis.get("has_goal"),
                "intent_text": intent_analysis.get("intent_text", ""),
                "goal_text": intent_analysis.get("goal_text", ""),
            },
            "dynamic_rules": {
                "matched": dynamic_rules.get("matched"),
                "matches": dynamic_rules.get("matches", []),
            },
        }
        provenance_hints = self._extract_provenance_hints(text, config)
        effective_threshold = int(profile_config.get("threshold", config.get("threshold", 2)))
        score = sum(self.weight_map.get(keyword, 1) for keyword in matched)
        score += sum(self.behavior_weights.get(key, 0) for key, value in behavior.items() if key in self.behavior_weights and value)
        score += dynamic_rules.get("weight", 0)
        score += 1 if trace_analysis.get("detected") else 0
        score += 1 if intent_analysis.get("has_intent") or intent_analysis.get("has_goal") else 0
        severity = self._severity(score)
        source_type, source_confidence, source_evidence = self._classify_source(text)
        risk_level, recommended_actions = self._risk_profile_from_config(source_type, source_confidence, profile_config)
        dynamic_risk, dynamic_actions = self._risk_from_dynamic_rules(dynamic_rules, profile_config)
        if dynamic_risk and self._risk_rank(dynamic_risk) > self._risk_rank(risk_level):
            risk_level = dynamic_risk
            recommended_actions = list(dict.fromkeys(dynamic_actions + recommended_actions))
        classification = self._classify_hierarchy(behavior, trace_analysis, intent_analysis, source_type, score, dynamic_rules, config, risk_level)
        summary_stats = {
            "flagged_files": 1 if (score >= 2 or "vibecode" in normalized or source_type != "unknown" or behavior.get("generated_code") or dynamic_rules.get("matched")) else 0,
            "source_type": source_type,
            "confidence": round(source_confidence, 2),
        }
        return {
            "is_vibecode": score >= effective_threshold or ("vibecode" in normalized and effective_threshold <= 1) or behavior.get("generated_code") or dynamic_rules.get("matched") or trace_analysis.get("detected") or intent_analysis.get("has_intent") or intent_analysis.get("has_goal"),
            "score": score,
            "severity": severity,
            "matched_keywords": matched,
            "source_type": source_type,
            "source_confidence": round(source_confidence, 2),
            "source_evidence": source_evidence,
            "risk_level": risk_level,
            "recommended_actions": recommended_actions,
            "summary": self._summary(matched, source_type, source_confidence),
            "summary_stats": summary_stats,
            "profile": profile_name,
            "threshold": effective_threshold,
            "policy": profile_config.get("policy", {}),
            "behavior": behavior,
            "trace_analysis": trace_analysis,
            "intent_analysis": intent_analysis,
            "dynamic_rules": dynamic_rules,
            "classification": classification,
            "evidence_breakdown": evidence_breakdown,
            "provenance_hints": provenance_hints,
        }

    def scan_paths(self, paths: List[str], config_path: Path | None = None, config: Dict | None = None) -> Dict:
        files = []
        config = config if config is not None else self.load_config(config_path)
        profile_name = config.get("profile") if isinstance(config, dict) else None
        profile_config = self._get_profile_config(config, profile_name)
        combined_score = 0
        matched_keywords: List[str] = []
        source_summary: Dict[str, int] = {}
        language_summary: Dict[str, int] = {}
        for raw_path in paths:
            path = Path(raw_path)
            if not path.exists():
                continue
            if path.is_dir():
                for item in sorted(path.rglob("*")):
                    if item.is_file():
                        text = item.read_text(encoding="utf-8", errors="ignore")
                        result = self.analyze(text, config_path=config_path, config=config)
                        if result["score"] or result["source_type"] != "unknown":
                            language = self._infer_language(str(item))
                            language_summary[language] = language_summary.get(language, 0) + 1
                            files.append({
                                "name": str(item),
                                "score": result["score"],
                                "keywords": result["matched_keywords"],
                                "source_type": result["source_type"],
                                "source_confidence": result["source_confidence"],
                                "source_evidence": result["source_evidence"],
                                "language": language,
                                "behavior": result.get("behavior", {}),
                                "trace_analysis": result.get("trace_analysis", {}),
                                "intent_analysis": result.get("intent_analysis", {}),
                                "classification": result.get("classification", {}),
                            })
                            combined_score += result["score"]
                            matched_keywords.extend(result["matched_keywords"])
                            source_summary[result["source_type"]] = source_summary.get(result["source_type"], 0) + 1
                continue
            if path.is_file():
                text = path.read_text(encoding="utf-8", errors="ignore")
                result = self.analyze(text, config_path=config_path, config=config)
                if result["score"] or result["source_type"] != "unknown":
                    language = self._infer_language(path.name)
                    language_summary[language] = language_summary.get(language, 0) + 1
                    files.append({
                        "name": path.name,
                        "score": result["score"],
                        "keywords": result["matched_keywords"],
                        "source_type": result["source_type"],
                        "source_confidence": result["source_confidence"],
                        "source_evidence": result["source_evidence"],
                        "language": language,
                        "behavior": result.get("behavior", {}),
                        "trace_analysis": result.get("trace_analysis", {}),
                        "intent_analysis": result.get("intent_analysis", {}),
                        "classification": result.get("classification", {}),
                    })
                    combined_score += result["score"]
                    matched_keywords.extend(result["matched_keywords"])
                    source_summary[result["source_type"]] = source_summary.get(result["source_type"], 0) + 1
        risk_level, recommended_actions = self._risk_profile(source_summary, language_summary, files)
        audit_summary = self._build_audit_summary(source_summary, language_summary, risk_level, recommended_actions)
        file_summary = self._build_file_summary(files)
        return {
            "is_vibecode": combined_score >= 2,
            "score": combined_score,
            "severity": self._severity(combined_score),
            "matched_keywords": sorted(set(matched_keywords)),
            "files": files,
            "source_summary": source_summary,
            "language_summary": language_summary,
            "summary_label": self._summary_label(source_summary, language_summary),
            "risk_level": risk_level,
            "recommended_actions": recommended_actions,
            "audit_summary": audit_summary,
            "file_summary": file_summary,
            "summary": self._summary(sorted(set(matched_keywords))),
            "profile": profile_name,
            "threshold": int(profile_config.get("threshold", config.get("threshold", 2))),
            "policy": profile_config.get("policy", {}),
            "summary_stats": {
                "flagged_files": len(files),
                "source_types": source_summary,
                "languages": language_summary,
                "risk_level": risk_level,
            },
        }

    def load_config(self, config_path: Path | None = None) -> Dict:
        target = config_path or Path(".specomega/vibecode_config.json")
        if not target.exists():
            return {}
        try:
            return json.loads(target.read_text(encoding="utf-8"))
        except Exception:
            return {}

    def _get_profile_config(self, config: Dict, profile_name: str | None) -> Dict:
        if not isinstance(config, dict):
            return config or {}
        profiles = config.get("profiles", {}) if isinstance(config.get("profiles", {}), dict) else {}
        if profile_name and profile_name in profiles:
            profile_cfg = profiles[profile_name]
            if isinstance(profile_cfg, dict):
                merged = dict(config)
                merged.pop("profiles", None)
                merged.pop("profile", None)
                merged.update(profile_cfg)
                if "rules" in profile_cfg and isinstance(profile_cfg.get("rules"), dict):
                    merged["rules"] = {**(config.get("rules", {}) or {}), **profile_cfg.get("rules", {})}
                if "policy" in profile_cfg and isinstance(profile_cfg.get("policy"), dict):
                    merged["policy"] = {**(config.get("policy", {}) or {}), **profile_cfg.get("policy", {})}
                return merged
        return config

    def _severity(self, score: int) -> str:
        if score >= 6:
            return "high"
        if score >= 3:
            return "medium"
        if score >= 1:
            return "low"
        return "none"

    def _extract_provenance_hints(self, text: str, config: Dict | None = None) -> List[str]:
        hints: List[str] = []
        if isinstance(config, dict):
            repositories = config.get("repository_sources", [])
            if isinstance(repositories, str):
                repositories = [repositories]
            if isinstance(repositories, list):
                for repository in repositories:
                    if isinstance(repository, str) and repository.strip():
                        hints.append(repository.strip().lower())
        patterns = [
            r"(?:source|provenance|origin)\s*[:=]\s*([A-Za-z0-9._/-]+(?:\s+[A-Za-z0-9._/-]+)*)",
            r"\b(local[- ]git[- ]server|github|gitlab|bitbucket)\b",
        ]
        for pattern in patterns:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                value = match.group(1).strip() if match.lastindex else match.group(0).strip()
                if value:
                    normalized = re.sub(r"\s+", "-", value).strip("-:/")
                    if normalized:
                        hints.append(normalized.lower())
        return sorted(set(hints))

    def _classify_source(self, text: str) -> tuple[str, float, List[str]]:
        normalized = (text or "").lower()
        llm_matches = [indicator for indicator in self.llm_indicators if indicator in normalized]
        template_matches = [indicator for indicator in self.template_indicators if indicator in normalized]
        code_matches = [pattern for pattern in self.code_structure_patterns if re.search(pattern, text, re.IGNORECASE)]

        if llm_matches:
            confidence = 0.9 if len(llm_matches) >= 2 else 0.8
            return "llm_generated", confidence, llm_matches
        if template_matches:
            confidence = 0.8 if len(template_matches) >= 2 else 0.7
            return "template_generated", confidence, template_matches
        if self._looks_like_code(text):
            confidence = 0.65 if code_matches else 0.6
            return "handwritten", confidence, code_matches or ["code structure"]
        return "unknown", 0.0, []

    def _contains_any(self, text: str, indicators: List[str]) -> bool:
        return any(indicator in text for indicator in indicators)

    def _looks_like_code(self, text: str) -> bool:
        if not text or not text.strip():
            return False
        if len(text.strip().splitlines()) <= 1 and len(text.strip()) < 40:
            return False
        return any(re.search(pattern, text, re.IGNORECASE) for pattern in self.code_structure_patterns)

    def _detect_behavior(self, text: str) -> Dict:
        normalized = (text or "").lower()
        evidence: List[str] = []
        generated_code = any(indicator in normalized for indicator in self.generation_indicators)
        autogenerated = any(indicator in normalized for indicator in ["autogenerated", "generated by", "generated with", "created by model", "synthesized"])
        template_like = any(indicator in normalized for indicator in self.template_indicators)
        trace_like = any(re.search(pattern, text, re.IGNORECASE) for pattern in self.trace_patterns)
        intent_like = any(re.search(pattern, text, re.IGNORECASE) for pattern in self.intent_patterns)
        if generated_code:
            evidence.append("generation indicators")
        if autogenerated:
            evidence.append("autogenerated markers")
        if template_like:
            evidence.append("template markers")
        if trace_like:
            evidence.append("trace markers")
        if intent_like:
            evidence.append("intent markers")
        confidence = round(min(1.0, 0.5 + 0.08 * len(evidence)), 2)
        return {
            "generated_code": generated_code,
            "autogenerated": autogenerated,
            "template_like": template_like,
            "trace_like": trace_like,
            "intent_like": intent_like,
            "evidence": evidence,
            "confidence": confidence,
        }

    def _analyze_trace(self, text: str) -> Dict:
        evidence: List[str] = []
        normalized = (text or "").lower()
        if "trace:" in normalized:
            match = re.search(r"trace\s*[:=]\s*([^\n;]+)", text, re.IGNORECASE)
            if match:
                trace_value = match.group(1).strip()
                evidence.append(trace_value)
                flow_match = re.search(r"([A-Za-z0-9_.-]+(?:\s*->\s*[A-Za-z0-9_.-]+)+)", trace_value)
                if flow_match:
                    evidence.append(flow_match.group(1).replace(" ", ""))
        direct_flow_match = re.search(r"(prompt\s*->\s*model\s*->\s*patch)", text, re.IGNORECASE)
        if direct_flow_match:
            evidence.append(direct_flow_match.group(1).replace(" ", ""))
        for pattern in [r"prompt\s*->", r"->\s*model", r"->\s*patch", r"workflow", r"pipeline", r"agent"]:
            if re.search(pattern, text, re.IGNORECASE):
                evidence.append(pattern)
        detected = bool(evidence)
        return {
            "detected": detected,
            "evidence": evidence,
            "confidence": round(min(1.0, 0.6 + 0.1 * len(evidence)), 2),
        }

    def _analyze_intent(self, text: str) -> Dict:
        intent_match = re.search(r"intent\s*[:=]\s*([^\n;]+)", text, re.IGNORECASE)
        goal_match = re.search(r"goal\s*[:=]\s*([^\n;]+)", text, re.IGNORECASE)
        objective_match = re.search(r"objective\s*[:=]\s*([^\n;]+)", text, re.IGNORECASE)
        aim_match = re.search(r"aim\s*[:=]\s*([^\n;]+)", text, re.IGNORECASE)
        intent_text = intent_match.group(1).strip() if intent_match else ""
        goal_text = goal_match.group(1).strip() if goal_match else (objective_match.group(1).strip() if objective_match else (aim_match.group(1).strip() if aim_match else ""))
        has_intent = bool(intent_text or any(marker in (text or "").lower() for marker in ["intent:", "deliver", "reduce", "improve", "support", "enable", "build", "implement"]))
        has_goal = bool(goal_text or any(marker in (text or "").lower() for marker in ["goal:", "objective:", "aim:", "purpose:", "reduce", "improve", "support", "enable", "build", "implement"]))
        return {
            "has_intent": has_intent,
            "has_goal": has_goal,
            "intent_text": intent_text,
            "goal_text": goal_text,
            "validated": has_intent and has_goal,
            "confidence": round(min(1.0, 0.55 + 0.1 * int(has_intent) + 0.1 * int(has_goal)), 2),
        }

    def _apply_dynamic_rules(self, text: str, config: Dict | None) -> Dict:
        if not isinstance(config, dict):
            return {"matched": False, "matches": [], "details": [], "weight": 0}
        rules = config.get("rules", {}) or {}
        if not isinstance(rules, dict):
            return {"matched": False, "matches": [], "details": [], "weight": 0}
        matches: List[str] = []
        details: List[Dict] = []
        total_weight = 0
        normalized = (text or "").lower()
        for rule_name, rule_cfg in rules.items():
            if not isinstance(rule_cfg, dict):
                continue
            patterns = rule_cfg.get("patterns", [])
            if isinstance(patterns, str):
                patterns = [patterns]
            if not isinstance(patterns, list):
                continue
            if any(re.search(pattern, text, re.IGNORECASE) for pattern in patterns if isinstance(pattern, str)):
                label = rule_cfg.get("label") or rule_name
                matches.append(label)
                weight = int(rule_cfg.get("weight", 1))
                total_weight += weight
                details.append({
                    "rule": rule_name,
                    "label": label,
                    "risk": rule_cfg.get("risk", "medium"),
                    "actions": rule_cfg.get("actions", []),
                    "weight": weight,
                    "category": rule_cfg.get("category", "dynamic"),
                    "evidence": [pattern for pattern in patterns if isinstance(pattern, str) and re.search(pattern, text, re.IGNORECASE)],
                })
        matched = bool(matches)
        return {
            "matched": matched,
            "matches": matches,
            "details": details,
            "weight": total_weight,
            "confidence": round(min(1.0, 0.6 + 0.08 * len(matches)), 2),
        }

    def _classify_hierarchy(self, behavior: Dict, trace_analysis: Dict, intent_analysis: Dict, source_type: str, score: int, dynamic_rules: Dict, config: Dict | None, risk_level: str) -> Dict:
        hierarchy = "layer:surface"
        if intent_analysis.get("has_intent") or intent_analysis.get("has_goal"):
            hierarchy = "layer:goal-driven"
        elif trace_analysis.get("detected"):
            hierarchy = "layer:trace-based"
        elif behavior.get("generated_code") or behavior.get("autogenerated"):
            hierarchy = "layer:generated-behavior"
        category = "manual"
        if behavior.get("generated_code") or behavior.get("autogenerated"):
            category = "generated_behavior"
        elif trace_analysis.get("detected"):
            category = "trace_behavior"
        elif intent_analysis.get("has_intent") or intent_analysis.get("has_goal"):
            category = "intent_goal"
        confirmations = []
        if behavior.get("generated_code"):
            confirmations.append("generated_code")
        if behavior.get("autogenerated"):
            confirmations.append("autogenerated")
        if trace_analysis.get("detected"):
            confirmations.append("trace")
        if intent_analysis.get("validated"):
            confirmations.append("intent_goal")
        if dynamic_rules.get("matched"):
            confirmations.append("dynamic_rule")
        if source_type != "unknown":
            confirmations.append(source_type)
        review_priority = "high" if risk_level == "high" else "medium" if risk_level == "medium" else "low"
        return {
            "hierarchy": hierarchy,
            "category": category,
            "risk_level": risk_level,
            "review_priority": review_priority,
            "confirmations": confirmations,
            "confidence": round(min(1.0, 0.55 + 0.05 * len(confirmations) + 0.01 * max(score, 0)), 2),
        }

    def _risk_from_dynamic_rules(self, dynamic_rules: Dict, config: Dict) -> tuple[str, List[str]]:
        if not dynamic_rules.get("matched"):
            return "", []
        highest_risk = "low"
        actions: List[str] = []
        for detail in dynamic_rules.get("details", []):
            risk = detail.get("risk", "medium")
            if self._risk_rank(risk) > self._risk_rank(highest_risk):
                highest_risk = risk
            actions.extend(detail.get("actions", []))
        return highest_risk, list(dict.fromkeys(actions))

    def _risk_rank(self, risk_level: str) -> int:
        order = {"low": 0, "medium": 1, "high": 2}
        return order.get((risk_level or "low").lower(), 0)

    def _summary(self, matched: List[str], source_type: str | None = None, confidence: float | None = None) -> str:
        if not matched:
            return "No Vibecode signals detected"
        base = "Detected Vibecode-related signals: " + ", ".join(matched)
        if source_type and source_type != "unknown":
            base += f" [source={source_type}]"
        if confidence is not None and confidence > 0:
            base += f" [confidence={confidence:.2f}]"
        return base

    def _infer_language(self, path_name: str) -> str:
        lowered = path_name.lower()
        if lowered.endswith((".py", ".pyi")):
            return "python"
        if lowered.endswith((".js", ".jsx", ".ts", ".tsx")):
            return "javascript"
        if lowered.endswith((".java", ".kt", ".scala")):
            return "java"
        if lowered.endswith((".go", ".rs")):
            return "systems"
        if lowered.endswith((".md", ".txt", ".rst")):
            return "docs"
        return "unknown"

    def _summary_label(self, source_summary: Dict[str, int], language_summary: Dict[str, int]) -> str:
        dominant_source = max(source_summary.items(), key=lambda item: item[1])[0] if source_summary else "unknown"
        dominant_language = max(language_summary.items(), key=lambda item: item[1])[0] if language_summary else "unknown"
        return f"governance: {dominant_source} across {dominant_language}"

    def _build_audit_summary(self, source_summary: Dict[str, int], language_summary: Dict[str, int], risk_level: str, recommended_actions: List[str]) -> Dict:
        return {
            "risk_level": risk_level,
            "recommended_actions": recommended_actions,
            "source_summary": source_summary,
            "language_summary": language_summary,
            "total_files": sum(source_summary.values()),
        }

    def _build_file_summary(self, files: List[dict]) -> List[Dict]:
        return [
            {
                "name": entry.get("name"),
                "language": entry.get("language", "unknown"),
                "source_type": entry.get("source_type", "unknown"),
                "confidence": entry.get("source_confidence", 0.0),
                "evidence": entry.get("source_evidence", []),
            }
            for entry in files
        ]

    def _risk_profile(self, source_summary: Dict[str, int], language_summary: Dict[str, int], files: List[dict]) -> tuple[str, List[str]]:
        risk_order = {"low": 0, "medium": 1, "high": 2}
        selected_level = "low"
        actions: List[str] = []
        for entry in files:
            level = entry.get("risk_level", "low")
            if risk_order.get(level, 0) > risk_order.get(selected_level, 0):
                selected_level = level
                actions = list(entry.get("recommended_actions", []))
            elif risk_order.get(level, 0) == risk_order.get(selected_level, 0):
                actions.extend(entry.get("recommended_actions", []))
        if not actions:
            llm_count = source_summary.get("llm_generated", 0)
            template_count = source_summary.get("template_generated", 0)
            if llm_count and llm_count >= max(1, len(files) // 2):
                return "high", [
                    "review AI-generated code for approval and provenance",
                    "require human validation before merge",
                ]
            if template_count and template_count >= max(1, len(files) // 2):
                return "medium", [
                    "inspect template scaffolds for customization quality",
                    "ensure boilerplate paths are documented and reviewed",
                ]
            if llm_count or template_count:
                return "medium", [
                    "mark generated code for manual review",
                    "capture provenance notes in the change record",
                ]
            return "low", [
                "keep current review flow",
                "retain source provenance notes for future audits",
            ]
        return selected_level, sorted(set(actions))

    def _risk_profile_from_config(self, source_type: str, confidence: float, config: Dict) -> tuple[str, List[str]]:
        rules = config.get("rules", {}) or {}
        rule = rules.get(source_type, {}) if isinstance(rules, dict) else {}
        if rule:
            risk = rule.get("risk", "medium")
            actions = rule.get("actions", [])
            if actions:
                return risk, actions
        if source_type == "llm_generated" and confidence >= 0.8:
            return "high", ["review AI-generated code for approval and provenance"]
        if source_type == "template_generated":
            return "medium", ["inspect template scaffolds for customization quality"]
        return "low", ["keep current review flow"]

    def evaluate_policy_gate(self, result: Dict, config: Dict) -> tuple[bool, str]:
        profile_name = config.get("profile") if isinstance(config, dict) else None
        effective_config = self._get_profile_config(config, profile_name)
        policy = effective_config.get("policy", {}) or {}
        if not isinstance(policy, dict):
            return False, "pass"
        threshold = policy.get("block_on", "medium")
        risk_level = result.get("risk_level", "low")
        if risk_level == "high" and threshold in {"high", "medium", "low"}:
            return True, "blocked"
        if risk_level == "medium" and threshold in {"medium", "low"}:
            return True, "blocked"
        return False, "pass"
