import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from specomega.analysis.vibecode import VibecodeAnalyzer


def main() -> None:
    config_path = ROOT / ".specomega" / "vibecode_config.json"
    config = json.loads(config_path.read_text(encoding="utf-8")) if config_path.exists() else {}
    if not config.get("repository_sources"):
        config["repository_sources"] = ["local-git-server", "internal-git"]
    sample_text = "Autogenerated by Copilot from a prompt. Trace: prompt->model->patch. Intent: deliver login flow. Goal: reduce manual review. Source: local-git-server. Workflow: planner->implementer->reviewer"
    analyzer = VibecodeAnalyzer()
    result = analyzer.analyze(sample_text, config=config)
    output_dir = ROOT / ".specomega" / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "vibecode_example.json").write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_dir / "vibecode_example.md").write_text("# Vibecode Example\n\n" + result.get("summary", "") + "\n", encoding="utf-8")
    print(json.dumps({"config": config, "result": {
        "summary": result.get("summary"),
        "evidence_breakdown": result.get("evidence_breakdown"),
        "provenance_hints": result.get("provenance_hints"),
        "risk_level": result.get("risk_level"),
    }}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
